/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as DiferenciaisRouteImport } from './routes/diferenciais'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParceirosIndexRouteImport } from './routes/parceiros.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ParceirosSlugRouteImport } from './routes/parceiros.$slug'
import { Route as AdminPrecosRouteImport } from './routes/admin/precos'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos.index'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DiferenciaisRoute = DiferenciaisRouteImport.update({
  id: '/diferenciais',
  path: '/diferenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosIndexRoute = ParceirosIndexRouteImport.update({
  id: '/parceiros/',
  path: '/parceiros/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ParceirosSlugRoute = ParceirosSlugRouteImport.update({
  id: '/parceiros/$slug',
  path: '/parceiros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/experiencia': typeof ExperienciaRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/orcamento': typeof OrcamentoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/parceiros/$slug': typeof ParceirosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/parceiros/': typeof ParceirosIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/experiencia': typeof ExperienciaRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/orcamento': typeof OrcamentoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/parceiros/$slug': typeof ParceirosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/parceiros': typeof ParceirosIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/experiencia': typeof ExperienciaRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/orcamento': typeof OrcamentoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/parceiros/$slug': typeof ParceirosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/parceiros/': typeof ParceirosIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design-system'
    | '/diferenciais'
    | '/experiencia'
    | '/galeria'
    | '/historia'
    | '/orcamento'
    | '/quem-somos'
    | '/admin/login'
    | '/admin/precos'
    | '/parceiros/$slug'
    | '/admin/'
    | '/parceiros/'
    | '/admin/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/diferenciais'
    | '/experiencia'
    | '/galeria'
    | '/historia'
    | '/orcamento'
    | '/quem-somos'
    | '/admin/login'
    | '/admin/precos'
    | '/parceiros/$slug'
    | '/admin'
    | '/parceiros'
    | '/admin/pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design-system'
    | '/diferenciais'
    | '/experiencia'
    | '/galeria'
    | '/historia'
    | '/orcamento'
    | '/quem-somos'
    | '/admin/login'
    | '/admin/precos'
    | '/parceiros/$slug'
    | '/admin/'
    | '/parceiros/'
    | '/admin/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  DiferenciaisRoute: typeof DiferenciaisRoute
  ExperienciaRoute: typeof ExperienciaRoute
  GaleriaRoute: typeof GaleriaRoute
  HistoriaRoute: typeof HistoriaRoute
  OrcamentoRoute: typeof OrcamentoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ParceirosSlugRoute: typeof ParceirosSlugRoute
  ParceirosIndexRoute: typeof ParceirosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diferenciais': {
      id: '/diferenciais'
      path: '/diferenciais'
      fullPath: '/diferenciais'
      preLoaderRoute: typeof DiferenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros/': {
      id: '/parceiros/'
      path: '/parceiros'
      fullPath: '/parceiros/'
      preLoaderRoute: typeof ParceirosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/parceiros/$slug': {
      id: '/parceiros/$slug'
      path: '/parceiros/$slug'
      fullPath: '/parceiros/$slug'
      preLoaderRoute: typeof ParceirosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  DiferenciaisRoute: DiferenciaisRoute,
  ExperienciaRoute: ExperienciaRoute,
  GaleriaRoute: GaleriaRoute,
  HistoriaRoute: HistoriaRoute,
  OrcamentoRoute: OrcamentoRoute,
  QuemSomosRoute: QuemSomosRoute,
  ParceirosSlugRoute: ParceirosSlugRoute,
  ParceirosIndexRoute: ParceirosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
