/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as EstruturaRouteImport } from './routes/estrutura'
import { Route as IndexRouteImport } from './routes/index'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaRoute = EstruturaRouteImport.update({
  id: '/estrutura',
  path: '/estrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estrutura': typeof EstruturaRoute
  '/experiencia': typeof ExperienciaRoute
  '/historia': typeof HistoriaRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estrutura': typeof EstruturaRoute
  '/experiencia': typeof ExperienciaRoute
  '/historia': typeof HistoriaRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estrutura': typeof EstruturaRoute
  '/experiencia': typeof ExperienciaRoute
  '/historia': typeof HistoriaRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estrutura' | '/experiencia' | '/historia' | '/quem-somos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estrutura' | '/experiencia' | '/historia' | '/quem-somos'
  id:
    | '__root__'
    | '/'
    | '/estrutura'
    | '/experiencia'
    | '/historia'
    | '/quem-somos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstruturaRoute: typeof EstruturaRoute
  ExperienciaRoute: typeof ExperienciaRoute
  HistoriaRoute: typeof HistoriaRoute
  QuemSomosRoute: typeof QuemSomosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura': {
      id: '/estrutura'
      path: '/estrutura'
      fullPath: '/estrutura'
      preLoaderRoute: typeof EstruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstruturaRoute: EstruturaRoute,
  ExperienciaRoute: ExperienciaRoute,
  HistoriaRoute: HistoriaRoute,
  QuemSomosRoute: QuemSomosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
